<?php
/**
 * SensorApi
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KiwiKi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use KiwiKi\ApiException;
use KiwiKi\Configuration;
use KiwiKi\HeaderSelector;
use KiwiKi\ObjectSerializer;

/**
 * SensorApi Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SensorApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1FriendlyNamesSensorSensorIdPost
     *
     * Assign a custom name to a sensor (friendly name)
     *
     * @param  \KiwiKi\Model\FnameData $fname_data fname_data (required)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KiwiKi\Model\FnameSet
     */
    public function v1FriendlyNamesSensorSensorIdPost($fname_data)
    {
        list($response) = $this->v1FriendlyNamesSensorSensorIdPostWithHttpInfo($fname_data);
        return $response;
    }

    /**
     * Operation v1FriendlyNamesSensorSensorIdPostWithHttpInfo
     *
     * Assign a custom name to a sensor (friendly name)
     *
     * @param  \KiwiKi\Model\FnameData $fname_data (required)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KiwiKi\Model\FnameSet, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1FriendlyNamesSensorSensorIdPostWithHttpInfo($fname_data)
    {
        $returnType = '\KiwiKi\Model\FnameSet';
        $request = $this->v1FriendlyNamesSensorSensorIdPostRequest($fname_data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KiwiKi\Model\FnameSet',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1FriendlyNamesSensorSensorIdPostAsync
     *
     * Assign a custom name to a sensor (friendly name)
     *
     * @param  \KiwiKi\Model\FnameData $fname_data (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1FriendlyNamesSensorSensorIdPostAsync($fname_data)
    {
        return $this->v1FriendlyNamesSensorSensorIdPostAsyncWithHttpInfo($fname_data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1FriendlyNamesSensorSensorIdPostAsyncWithHttpInfo
     *
     * Assign a custom name to a sensor (friendly name)
     *
     * @param  \KiwiKi\Model\FnameData $fname_data (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1FriendlyNamesSensorSensorIdPostAsyncWithHttpInfo($fname_data)
    {
        $returnType = '\KiwiKi\Model\FnameSet';
        $request = $this->v1FriendlyNamesSensorSensorIdPostRequest($fname_data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1FriendlyNamesSensorSensorIdPost'
     *
     * @param  \KiwiKi\Model\FnameData $fname_data (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1FriendlyNamesSensorSensorIdPostRequest($fname_data)
    {
        // verify the required parameter 'fname_data' is set
        if ($fname_data === null || (is_array($fname_data) && count($fname_data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fname_data when calling v1FriendlyNamesSensorSensorIdPost'
            );
        }

        $resourcePath = '/v1/friendly_names/sensor/{sensor_id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($fname_data)) {
            $_tempBody = $fname_data;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Session-Key');
        if ($apiKey !== null) {
            $headers['Session-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1SensorsGet
     *
     * Get a list of visible sensors
     *
     * @param  float $lat Latitude (coordinate) in radians (optional)
     * @param  float $lng Longitude (coordinate) in radians (optional)
     * @param  float $max_distance Maximal distance from specified coordinates in kilometers (optional)
     * @param  string $specifier Match on &#x60;specifier&#x60; sensor property (optional)
     * @param  string $street Street name of sensor&#39;s address (optional)
     * @param  string $city City where sensor is located (optional)
     * @param  string $state Province (Land) of sensor&#39;s address (optional)
     * @param  int $postal_code Postal code (Postleitzahl) of sensor&#39;s address (optional)
     * @param  string $permission Require at least permission level X that user has over a sensor (optional)
     * @param  int $page_size Maximal count of sensor in result list (optional, default to 20)
     * @param  int $page_number Number of page in paginated results (optional, default to 1)
     * @param  string $sort_by Field to sort results by (optional)
     * @param  string $order_by Direction of sorting results (optional)
     * @param  object $search Fuzzy case-insensitive search through &#x60;specifier&#x60;, &#x60;street&#x60;, &#x60;postal_code&#x60; and &#x60;city&#x60; at once. (optional)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KiwiKi\Model\SensorResult
     */
    public function v1SensorsGet($lat = null, $lng = null, $max_distance = null, $specifier = null, $street = null, $city = null, $state = null, $postal_code = null, $permission = null, $page_size = '20', $page_number = '1', $sort_by = null, $order_by = null, $search = null)
    {
        list($response) = $this->v1SensorsGetWithHttpInfo($lat, $lng, $max_distance, $specifier, $street, $city, $state, $postal_code, $permission, $page_size, $page_number, $sort_by, $order_by, $search);
        return $response;
    }

    /**
     * Operation v1SensorsGetWithHttpInfo
     *
     * Get a list of visible sensors
     *
     * @param  float $lat Latitude (coordinate) in radians (optional)
     * @param  float $lng Longitude (coordinate) in radians (optional)
     * @param  float $max_distance Maximal distance from specified coordinates in kilometers (optional)
     * @param  string $specifier Match on &#x60;specifier&#x60; sensor property (optional)
     * @param  string $street Street name of sensor&#39;s address (optional)
     * @param  string $city City where sensor is located (optional)
     * @param  string $state Province (Land) of sensor&#39;s address (optional)
     * @param  int $postal_code Postal code (Postleitzahl) of sensor&#39;s address (optional)
     * @param  string $permission Require at least permission level X that user has over a sensor (optional)
     * @param  int $page_size Maximal count of sensor in result list (optional, default to 20)
     * @param  int $page_number Number of page in paginated results (optional, default to 1)
     * @param  string $sort_by Field to sort results by (optional)
     * @param  string $order_by Direction of sorting results (optional)
     * @param  object $search Fuzzy case-insensitive search through &#x60;specifier&#x60;, &#x60;street&#x60;, &#x60;postal_code&#x60; and &#x60;city&#x60; at once. (optional)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KiwiKi\Model\SensorResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SensorsGetWithHttpInfo($lat = null, $lng = null, $max_distance = null, $specifier = null, $street = null, $city = null, $state = null, $postal_code = null, $permission = null, $page_size = '20', $page_number = '1', $sort_by = null, $order_by = null, $search = null)
    {
        $returnType = '\KiwiKi\Model\SensorResult';
        $request = $this->v1SensorsGetRequest($lat, $lng, $max_distance, $specifier, $street, $city, $state, $postal_code, $permission, $page_size, $page_number, $sort_by, $order_by, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KiwiKi\Model\SensorResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1SensorsGetAsync
     *
     * Get a list of visible sensors
     *
     * @param  float $lat Latitude (coordinate) in radians (optional)
     * @param  float $lng Longitude (coordinate) in radians (optional)
     * @param  float $max_distance Maximal distance from specified coordinates in kilometers (optional)
     * @param  string $specifier Match on &#x60;specifier&#x60; sensor property (optional)
     * @param  string $street Street name of sensor&#39;s address (optional)
     * @param  string $city City where sensor is located (optional)
     * @param  string $state Province (Land) of sensor&#39;s address (optional)
     * @param  int $postal_code Postal code (Postleitzahl) of sensor&#39;s address (optional)
     * @param  string $permission Require at least permission level X that user has over a sensor (optional)
     * @param  int $page_size Maximal count of sensor in result list (optional, default to 20)
     * @param  int $page_number Number of page in paginated results (optional, default to 1)
     * @param  string $sort_by Field to sort results by (optional)
     * @param  string $order_by Direction of sorting results (optional)
     * @param  object $search Fuzzy case-insensitive search through &#x60;specifier&#x60;, &#x60;street&#x60;, &#x60;postal_code&#x60; and &#x60;city&#x60; at once. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsGetAsync($lat = null, $lng = null, $max_distance = null, $specifier = null, $street = null, $city = null, $state = null, $postal_code = null, $permission = null, $page_size = '20', $page_number = '1', $sort_by = null, $order_by = null, $search = null)
    {
        return $this->v1SensorsGetAsyncWithHttpInfo($lat, $lng, $max_distance, $specifier, $street, $city, $state, $postal_code, $permission, $page_size, $page_number, $sort_by, $order_by, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SensorsGetAsyncWithHttpInfo
     *
     * Get a list of visible sensors
     *
     * @param  float $lat Latitude (coordinate) in radians (optional)
     * @param  float $lng Longitude (coordinate) in radians (optional)
     * @param  float $max_distance Maximal distance from specified coordinates in kilometers (optional)
     * @param  string $specifier Match on &#x60;specifier&#x60; sensor property (optional)
     * @param  string $street Street name of sensor&#39;s address (optional)
     * @param  string $city City where sensor is located (optional)
     * @param  string $state Province (Land) of sensor&#39;s address (optional)
     * @param  int $postal_code Postal code (Postleitzahl) of sensor&#39;s address (optional)
     * @param  string $permission Require at least permission level X that user has over a sensor (optional)
     * @param  int $page_size Maximal count of sensor in result list (optional, default to 20)
     * @param  int $page_number Number of page in paginated results (optional, default to 1)
     * @param  string $sort_by Field to sort results by (optional)
     * @param  string $order_by Direction of sorting results (optional)
     * @param  object $search Fuzzy case-insensitive search through &#x60;specifier&#x60;, &#x60;street&#x60;, &#x60;postal_code&#x60; and &#x60;city&#x60; at once. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsGetAsyncWithHttpInfo($lat = null, $lng = null, $max_distance = null, $specifier = null, $street = null, $city = null, $state = null, $postal_code = null, $permission = null, $page_size = '20', $page_number = '1', $sort_by = null, $order_by = null, $search = null)
    {
        $returnType = '\KiwiKi\Model\SensorResult';
        $request = $this->v1SensorsGetRequest($lat, $lng, $max_distance, $specifier, $street, $city, $state, $postal_code, $permission, $page_size, $page_number, $sort_by, $order_by, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SensorsGet'
     *
     * @param  float $lat Latitude (coordinate) in radians (optional)
     * @param  float $lng Longitude (coordinate) in radians (optional)
     * @param  float $max_distance Maximal distance from specified coordinates in kilometers (optional)
     * @param  string $specifier Match on &#x60;specifier&#x60; sensor property (optional)
     * @param  string $street Street name of sensor&#39;s address (optional)
     * @param  string $city City where sensor is located (optional)
     * @param  string $state Province (Land) of sensor&#39;s address (optional)
     * @param  int $postal_code Postal code (Postleitzahl) of sensor&#39;s address (optional)
     * @param  string $permission Require at least permission level X that user has over a sensor (optional)
     * @param  int $page_size Maximal count of sensor in result list (optional, default to 20)
     * @param  int $page_number Number of page in paginated results (optional, default to 1)
     * @param  string $sort_by Field to sort results by (optional)
     * @param  string $order_by Direction of sorting results (optional)
     * @param  object $search Fuzzy case-insensitive search through &#x60;specifier&#x60;, &#x60;street&#x60;, &#x60;postal_code&#x60; and &#x60;city&#x60; at once. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1SensorsGetRequest($lat = null, $lng = null, $max_distance = null, $specifier = null, $street = null, $city = null, $state = null, $postal_code = null, $permission = null, $page_size = '20', $page_number = '1', $sort_by = null, $order_by = null, $search = null)
    {

        $resourcePath = '/v1/sensors/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lat !== null) {
            $queryParams['lat'] = ObjectSerializer::toQueryValue($lat);
        }
        // query params
        if ($lng !== null) {
            $queryParams['lng'] = ObjectSerializer::toQueryValue($lng);
        }
        // query params
        if ($max_distance !== null) {
            $queryParams['max_distance'] = ObjectSerializer::toQueryValue($max_distance);
        }
        // query params
        if ($specifier !== null) {
            $queryParams['specifier'] = ObjectSerializer::toQueryValue($specifier);
        }
        // query params
        if ($street !== null) {
            $queryParams['street'] = ObjectSerializer::toQueryValue($street);
        }
        // query params
        if ($city !== null) {
            $queryParams['city'] = ObjectSerializer::toQueryValue($city);
        }
        // query params
        if ($state !== null) {
            $queryParams['state'] = ObjectSerializer::toQueryValue($state);
        }
        // query params
        if ($postal_code !== null) {
            $queryParams['postal_code'] = ObjectSerializer::toQueryValue($postal_code);
        }
        // query params
        if ($permission !== null) {
            $queryParams['permission'] = ObjectSerializer::toQueryValue($permission);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['page_size'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['page_number'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sort_by'] = ObjectSerializer::toQueryValue($sort_by);
        }
        // query params
        if ($order_by !== null) {
            $queryParams['order_by'] = ObjectSerializer::toQueryValue($order_by);
        }
        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Session-Key');
        if ($apiKey !== null) {
            $headers['Session-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1SensorsSensorIdActActionPost
     *
     * Send a command to a sensor
     *
     * @param  int $sensor_id sensor_id (required)
     * @param  string $action action (required)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v1SensorsSensorIdActActionPost($sensor_id, $action)
    {
        $this->v1SensorsSensorIdActActionPostWithHttpInfo($sensor_id, $action);
    }

    /**
     * Operation v1SensorsSensorIdActActionPostWithHttpInfo
     *
     * Send a command to a sensor
     *
     * @param  int $sensor_id (required)
     * @param  string $action (required)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SensorsSensorIdActActionPostWithHttpInfo($sensor_id, $action)
    {
        $returnType = '';
        $request = $this->v1SensorsSensorIdActActionPostRequest($sensor_id, $action);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v1SensorsSensorIdActActionPostAsync
     *
     * Send a command to a sensor
     *
     * @param  int $sensor_id (required)
     * @param  string $action (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsSensorIdActActionPostAsync($sensor_id, $action)
    {
        return $this->v1SensorsSensorIdActActionPostAsyncWithHttpInfo($sensor_id, $action)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SensorsSensorIdActActionPostAsyncWithHttpInfo
     *
     * Send a command to a sensor
     *
     * @param  int $sensor_id (required)
     * @param  string $action (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsSensorIdActActionPostAsyncWithHttpInfo($sensor_id, $action)
    {
        $returnType = '';
        $request = $this->v1SensorsSensorIdActActionPostRequest($sensor_id, $action);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SensorsSensorIdActActionPost'
     *
     * @param  int $sensor_id (required)
     * @param  string $action (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1SensorsSensorIdActActionPostRequest($sensor_id, $action)
    {
        // verify the required parameter 'sensor_id' is set
        if ($sensor_id === null || (is_array($sensor_id) && count($sensor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sensor_id when calling v1SensorsSensorIdActActionPost'
            );
        }
        // verify the required parameter 'action' is set
        if ($action === null || (is_array($action) && count($action) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $action when calling v1SensorsSensorIdActActionPost'
            );
        }

        $resourcePath = '/v1/sensors/{sensor_id}/act/{action}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sensor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sensor_id' . '}',
                ObjectSerializer::toPathValue($sensor_id),
                $resourcePath
            );
        }
        // path params
        if ($action !== null) {
            $resourcePath = str_replace(
                '{' . 'action' . '}',
                ObjectSerializer::toPathValue($action),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Session-Key');
        if ($apiKey !== null) {
            $headers['Session-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1SensorsSensorIdGet
     *
     * Get sensor details
     *
     * @param  int $sensor_id sensor_id (required)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KiwiKi\Model\SensorSingleResult
     */
    public function v1SensorsSensorIdGet($sensor_id)
    {
        list($response) = $this->v1SensorsSensorIdGetWithHttpInfo($sensor_id);
        return $response;
    }

    /**
     * Operation v1SensorsSensorIdGetWithHttpInfo
     *
     * Get sensor details
     *
     * @param  int $sensor_id (required)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KiwiKi\Model\SensorSingleResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SensorsSensorIdGetWithHttpInfo($sensor_id)
    {
        $returnType = '\KiwiKi\Model\SensorSingleResult';
        $request = $this->v1SensorsSensorIdGetRequest($sensor_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KiwiKi\Model\SensorSingleResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1SensorsSensorIdGetAsync
     *
     * Get sensor details
     *
     * @param  int $sensor_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsSensorIdGetAsync($sensor_id)
    {
        return $this->v1SensorsSensorIdGetAsyncWithHttpInfo($sensor_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SensorsSensorIdGetAsyncWithHttpInfo
     *
     * Get sensor details
     *
     * @param  int $sensor_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsSensorIdGetAsyncWithHttpInfo($sensor_id)
    {
        $returnType = '\KiwiKi\Model\SensorSingleResult';
        $request = $this->v1SensorsSensorIdGetRequest($sensor_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SensorsSensorIdGet'
     *
     * @param  int $sensor_id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1SensorsSensorIdGetRequest($sensor_id)
    {
        // verify the required parameter 'sensor_id' is set
        if ($sensor_id === null || (is_array($sensor_id) && count($sensor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sensor_id when calling v1SensorsSensorIdGet'
            );
        }

        $resourcePath = '/v1/sensors/{sensor_id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($sensor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sensor_id' . '}',
                ObjectSerializer::toPathValue($sensor_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Session-Key');
        if ($apiKey !== null) {
            $headers['Session-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1SensorsSensorIdPermissionsGet
     *
     * Get sensor permissions
     *
     * @param  int $sensor_id sensor_id (required)
     * @param  \DateTime $begins Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;ends&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  \DateTime $ends Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;begins&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  string[] $timing_state Filter by timing state of a permission. (optional)
     * @param  string[] $granted Filter by permission type. (optional)
     * @param  string $granted_by Filter by username/email of the user that granted a permission. (optional)
     * @param  string $username Filter by username/email of the user that a permission has been granted. (optional)
     * @param  string $name Filter by forename of the user that a permission has been granted. (optional)
     * @param  string $lastname Filter by last name of the user that a permission has been granted. (optional)
     * @param  string[] $segment_id Filter by segment of the user that a permission has been granted.   * &#x60;00&#x60; - KIWI employee   * &#x60;05&#x60; - KIWI electrician   * &#x60;10&#x60; - Resident   * &#x60;15&#x60; - Resident (special)   * &#x60;20&#x60; - Small business employee   * &#x60;25&#x60; - Small business employee (special)   * &#x60;30&#x60; - Employee   * &#x60;35&#x60; - Employee (special)   * &#x60;40&#x60; - Service provider   * &#x60;45&#x60; - Service provider (special)   * &#x60;50&#x60; - Partner   * &#x60;55&#x60; - Partner (special) (optional)
     * @param  int $page_size Maximal number of items per page. (optional, default to 20)
     * @param  int $page_number Number of page in paginated results. (optional, default to 1)
     * @param  string $sort_by Field to sort results by. (optional, default to permission_id)
     * @param  string $order_by Direction of sorting results. (optional, default to asc)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \KiwiKi\Model\SensorPermissionsResult
     */
    public function v1SensorsSensorIdPermissionsGet($sensor_id, $begins = null, $ends = null, $timing_state = null, $granted = null, $granted_by = null, $username = null, $name = null, $lastname = null, $segment_id = null, $page_size = '20', $page_number = '1', $sort_by = 'permission_id', $order_by = 'asc')
    {
        list($response) = $this->v1SensorsSensorIdPermissionsGetWithHttpInfo($sensor_id, $begins, $ends, $timing_state, $granted, $granted_by, $username, $name, $lastname, $segment_id, $page_size, $page_number, $sort_by, $order_by);
        return $response;
    }

    /**
     * Operation v1SensorsSensorIdPermissionsGetWithHttpInfo
     *
     * Get sensor permissions
     *
     * @param  int $sensor_id (required)
     * @param  \DateTime $begins Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;ends&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  \DateTime $ends Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;begins&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  string[] $timing_state Filter by timing state of a permission. (optional)
     * @param  string[] $granted Filter by permission type. (optional)
     * @param  string $granted_by Filter by username/email of the user that granted a permission. (optional)
     * @param  string $username Filter by username/email of the user that a permission has been granted. (optional)
     * @param  string $name Filter by forename of the user that a permission has been granted. (optional)
     * @param  string $lastname Filter by last name of the user that a permission has been granted. (optional)
     * @param  string[] $segment_id Filter by segment of the user that a permission has been granted.   * &#x60;00&#x60; - KIWI employee   * &#x60;05&#x60; - KIWI electrician   * &#x60;10&#x60; - Resident   * &#x60;15&#x60; - Resident (special)   * &#x60;20&#x60; - Small business employee   * &#x60;25&#x60; - Small business employee (special)   * &#x60;30&#x60; - Employee   * &#x60;35&#x60; - Employee (special)   * &#x60;40&#x60; - Service provider   * &#x60;45&#x60; - Service provider (special)   * &#x60;50&#x60; - Partner   * &#x60;55&#x60; - Partner (special) (optional)
     * @param  int $page_size Maximal number of items per page. (optional, default to 20)
     * @param  int $page_number Number of page in paginated results. (optional, default to 1)
     * @param  string $sort_by Field to sort results by. (optional, default to permission_id)
     * @param  string $order_by Direction of sorting results. (optional, default to asc)
     *
     * @throws \KiwiKi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \KiwiKi\Model\SensorPermissionsResult, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1SensorsSensorIdPermissionsGetWithHttpInfo($sensor_id, $begins = null, $ends = null, $timing_state = null, $granted = null, $granted_by = null, $username = null, $name = null, $lastname = null, $segment_id = null, $page_size = '20', $page_number = '1', $sort_by = 'permission_id', $order_by = 'asc')
    {
        $returnType = '\KiwiKi\Model\SensorPermissionsResult';
        $request = $this->v1SensorsSensorIdPermissionsGetRequest($sensor_id, $begins, $ends, $timing_state, $granted, $granted_by, $username, $name, $lastname, $segment_id, $page_size, $page_number, $sort_by, $order_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\KiwiKi\Model\SensorPermissionsResult',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1SensorsSensorIdPermissionsGetAsync
     *
     * Get sensor permissions
     *
     * @param  int $sensor_id (required)
     * @param  \DateTime $begins Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;ends&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  \DateTime $ends Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;begins&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  string[] $timing_state Filter by timing state of a permission. (optional)
     * @param  string[] $granted Filter by permission type. (optional)
     * @param  string $granted_by Filter by username/email of the user that granted a permission. (optional)
     * @param  string $username Filter by username/email of the user that a permission has been granted. (optional)
     * @param  string $name Filter by forename of the user that a permission has been granted. (optional)
     * @param  string $lastname Filter by last name of the user that a permission has been granted. (optional)
     * @param  string[] $segment_id Filter by segment of the user that a permission has been granted.   * &#x60;00&#x60; - KIWI employee   * &#x60;05&#x60; - KIWI electrician   * &#x60;10&#x60; - Resident   * &#x60;15&#x60; - Resident (special)   * &#x60;20&#x60; - Small business employee   * &#x60;25&#x60; - Small business employee (special)   * &#x60;30&#x60; - Employee   * &#x60;35&#x60; - Employee (special)   * &#x60;40&#x60; - Service provider   * &#x60;45&#x60; - Service provider (special)   * &#x60;50&#x60; - Partner   * &#x60;55&#x60; - Partner (special) (optional)
     * @param  int $page_size Maximal number of items per page. (optional, default to 20)
     * @param  int $page_number Number of page in paginated results. (optional, default to 1)
     * @param  string $sort_by Field to sort results by. (optional, default to permission_id)
     * @param  string $order_by Direction of sorting results. (optional, default to asc)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsSensorIdPermissionsGetAsync($sensor_id, $begins = null, $ends = null, $timing_state = null, $granted = null, $granted_by = null, $username = null, $name = null, $lastname = null, $segment_id = null, $page_size = '20', $page_number = '1', $sort_by = 'permission_id', $order_by = 'asc')
    {
        return $this->v1SensorsSensorIdPermissionsGetAsyncWithHttpInfo($sensor_id, $begins, $ends, $timing_state, $granted, $granted_by, $username, $name, $lastname, $segment_id, $page_size, $page_number, $sort_by, $order_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1SensorsSensorIdPermissionsGetAsyncWithHttpInfo
     *
     * Get sensor permissions
     *
     * @param  int $sensor_id (required)
     * @param  \DateTime $begins Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;ends&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  \DateTime $ends Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;begins&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  string[] $timing_state Filter by timing state of a permission. (optional)
     * @param  string[] $granted Filter by permission type. (optional)
     * @param  string $granted_by Filter by username/email of the user that granted a permission. (optional)
     * @param  string $username Filter by username/email of the user that a permission has been granted. (optional)
     * @param  string $name Filter by forename of the user that a permission has been granted. (optional)
     * @param  string $lastname Filter by last name of the user that a permission has been granted. (optional)
     * @param  string[] $segment_id Filter by segment of the user that a permission has been granted.   * &#x60;00&#x60; - KIWI employee   * &#x60;05&#x60; - KIWI electrician   * &#x60;10&#x60; - Resident   * &#x60;15&#x60; - Resident (special)   * &#x60;20&#x60; - Small business employee   * &#x60;25&#x60; - Small business employee (special)   * &#x60;30&#x60; - Employee   * &#x60;35&#x60; - Employee (special)   * &#x60;40&#x60; - Service provider   * &#x60;45&#x60; - Service provider (special)   * &#x60;50&#x60; - Partner   * &#x60;55&#x60; - Partner (special) (optional)
     * @param  int $page_size Maximal number of items per page. (optional, default to 20)
     * @param  int $page_number Number of page in paginated results. (optional, default to 1)
     * @param  string $sort_by Field to sort results by. (optional, default to permission_id)
     * @param  string $order_by Direction of sorting results. (optional, default to asc)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1SensorsSensorIdPermissionsGetAsyncWithHttpInfo($sensor_id, $begins = null, $ends = null, $timing_state = null, $granted = null, $granted_by = null, $username = null, $name = null, $lastname = null, $segment_id = null, $page_size = '20', $page_number = '1', $sort_by = 'permission_id', $order_by = 'asc')
    {
        $returnType = '\KiwiKi\Model\SensorPermissionsResult';
        $request = $this->v1SensorsSensorIdPermissionsGetRequest($sensor_id, $begins, $ends, $timing_state, $granted, $granted_by, $username, $name, $lastname, $segment_id, $page_size, $page_number, $sort_by, $order_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1SensorsSensorIdPermissionsGet'
     *
     * @param  int $sensor_id (required)
     * @param  \DateTime $begins Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;ends&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  \DateTime $ends Filter by date time range. Permissions that overlap with the specified timespan (inclusive) will be included in the result (see &#x60;begins&#x60; parameter). Timezone needs to be specified. (optional)
     * @param  string[] $timing_state Filter by timing state of a permission. (optional)
     * @param  string[] $granted Filter by permission type. (optional)
     * @param  string $granted_by Filter by username/email of the user that granted a permission. (optional)
     * @param  string $username Filter by username/email of the user that a permission has been granted. (optional)
     * @param  string $name Filter by forename of the user that a permission has been granted. (optional)
     * @param  string $lastname Filter by last name of the user that a permission has been granted. (optional)
     * @param  string[] $segment_id Filter by segment of the user that a permission has been granted.   * &#x60;00&#x60; - KIWI employee   * &#x60;05&#x60; - KIWI electrician   * &#x60;10&#x60; - Resident   * &#x60;15&#x60; - Resident (special)   * &#x60;20&#x60; - Small business employee   * &#x60;25&#x60; - Small business employee (special)   * &#x60;30&#x60; - Employee   * &#x60;35&#x60; - Employee (special)   * &#x60;40&#x60; - Service provider   * &#x60;45&#x60; - Service provider (special)   * &#x60;50&#x60; - Partner   * &#x60;55&#x60; - Partner (special) (optional)
     * @param  int $page_size Maximal number of items per page. (optional, default to 20)
     * @param  int $page_number Number of page in paginated results. (optional, default to 1)
     * @param  string $sort_by Field to sort results by. (optional, default to permission_id)
     * @param  string $order_by Direction of sorting results. (optional, default to asc)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1SensorsSensorIdPermissionsGetRequest($sensor_id, $begins = null, $ends = null, $timing_state = null, $granted = null, $granted_by = null, $username = null, $name = null, $lastname = null, $segment_id = null, $page_size = '20', $page_number = '1', $sort_by = 'permission_id', $order_by = 'asc')
    {
        // verify the required parameter 'sensor_id' is set
        if ($sensor_id === null || (is_array($sensor_id) && count($sensor_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sensor_id when calling v1SensorsSensorIdPermissionsGet'
            );
        }

        $resourcePath = '/v1/sensors/{sensor_id}/permissions/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($begins !== null) {
            $queryParams['begins'] = ObjectSerializer::toQueryValue($begins);
        }
        // query params
        if ($ends !== null) {
            $queryParams['ends'] = ObjectSerializer::toQueryValue($ends);
        }
        // query params
        if (is_array($timing_state)) {
            $queryParams['timing_state'] = $timing_state;
        } else
        if ($timing_state !== null) {
            $queryParams['timing_state'] = ObjectSerializer::toQueryValue($timing_state);
        }
        // query params
        if (is_array($granted)) {
            $queryParams['granted'] = $granted;
        } else
        if ($granted !== null) {
            $queryParams['granted'] = ObjectSerializer::toQueryValue($granted);
        }
        // query params
        if ($granted_by !== null) {
            $queryParams['granted_by'] = ObjectSerializer::toQueryValue($granted_by);
        }
        // query params
        if ($username !== null) {
            $queryParams['username'] = ObjectSerializer::toQueryValue($username);
        }
        // query params
        if ($name !== null) {
            $queryParams['name'] = ObjectSerializer::toQueryValue($name);
        }
        // query params
        if ($lastname !== null) {
            $queryParams['lastname'] = ObjectSerializer::toQueryValue($lastname);
        }
        // query params
        if (is_array($segment_id)) {
            $queryParams['segment_id'] = $segment_id;
        } else
        if ($segment_id !== null) {
            $queryParams['segment_id'] = ObjectSerializer::toQueryValue($segment_id);
        }
        // query params
        if ($page_size !== null) {
            $queryParams['page_size'] = ObjectSerializer::toQueryValue($page_size);
        }
        // query params
        if ($page_number !== null) {
            $queryParams['page_number'] = ObjectSerializer::toQueryValue($page_number);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sort_by'] = ObjectSerializer::toQueryValue($sort_by);
        }
        // query params
        if ($order_by !== null) {
            $queryParams['order_by'] = ObjectSerializer::toQueryValue($order_by);
        }

        // path params
        if ($sensor_id !== null) {
            $resourcePath = str_replace(
                '{' . 'sensor_id' . '}',
                ObjectSerializer::toPathValue($sensor_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Session-Key');
        if ($apiKey !== null) {
            $headers['Session-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
