<?php
/**
 * PermissionData1
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KiwiKi\Model;

use \ArrayAccess;
use \KiwiKi\ObjectSerializer;

/**
 * PermissionData1 Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PermissionData1 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'permission_data_1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'begins' => '\DateTime',
        'ends' => '\DateTime',
        'timeofday_begins' => 'string',
        'timeofday_ends' => 'string',
        'weekdays' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'begins' => 'date-time',
        'ends' => 'date-time',
        'timeofday_begins' => 'time',
        'timeofday_ends' => 'time',
        'weekdays' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'begins' => 'begins',
        'ends' => 'ends',
        'timeofday_begins' => 'timeofday_begins',
        'timeofday_ends' => 'timeofday_ends',
        'weekdays' => 'weekdays'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'begins' => 'setBegins',
        'ends' => 'setEnds',
        'timeofday_begins' => 'setTimeofdayBegins',
        'timeofday_ends' => 'setTimeofdayEnds',
        'weekdays' => 'setWeekdays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'begins' => 'getBegins',
        'ends' => 'getEnds',
        'timeofday_begins' => 'getTimeofdayBegins',
        'timeofday_ends' => 'getTimeofdayEnds',
        'weekdays' => 'getWeekdays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['begins'] = isset($data['begins']) ? $data['begins'] : null;
        $this->container['ends'] = isset($data['ends']) ? $data['ends'] : null;
        $this->container['timeofday_begins'] = isset($data['timeofday_begins']) ? $data['timeofday_begins'] : null;
        $this->container['timeofday_ends'] = isset($data['timeofday_ends']) ? $data['timeofday_ends'] : null;
        $this->container['weekdays'] = isset($data['weekdays']) ? $data['weekdays'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets begins
     *
     * @return \DateTime
     */
    public function getBegins()
    {
        return $this->container['begins'];
    }

    /**
     * Sets begins
     *
     * @param \DateTime $begins Start date of the permission without timezone offset. Europe/Berlin timezone is assumed.
     *
     * @return $this
     */
    public function setBegins($begins)
    {
        $this->container['begins'] = $begins;

        return $this;
    }

    /**
     * Gets ends
     *
     * @return \DateTime
     */
    public function getEnds()
    {
        return $this->container['ends'];
    }

    /**
     * Sets ends
     *
     * @param \DateTime $ends Expiration date of the permission without timezone offset. Europe/Berlin timezone is assumed.
     *
     * @return $this
     */
    public function setEnds($ends)
    {
        $this->container['ends'] = $ends;

        return $this;
    }

    /**
     * Gets timeofday_begins
     *
     * @return string
     */
    public function getTimeofdayBegins()
    {
        return $this->container['timeofday_begins'];
    }

    /**
     * Sets timeofday_begins
     *
     * @param string $timeofday_begins Start time of the permission on each day. Europe/Berlin timezone is assumed.
     *
     * @return $this
     */
    public function setTimeofdayBegins($timeofday_begins)
    {
        $this->container['timeofday_begins'] = $timeofday_begins;

        return $this;
    }

    /**
     * Gets timeofday_ends
     *
     * @return string
     */
    public function getTimeofdayEnds()
    {
        return $this->container['timeofday_ends'];
    }

    /**
     * Sets timeofday_ends
     *
     * @param string $timeofday_ends End time of the permission on each day. Europe/Berlin timezone is assumed.
     *
     * @return $this
     */
    public function setTimeofdayEnds($timeofday_ends)
    {
        $this->container['timeofday_ends'] = $timeofday_ends;

        return $this;
    }

    /**
     * Gets weekdays
     *
     * @return string
     */
    public function getWeekdays()
    {
        return $this->container['weekdays'];
    }

    /**
     * Sets weekdays
     *
     * @param string $weekdays Weekdays on which the permission should be active.
     *
     * @return $this
     */
    public function setWeekdays($weekdays)
    {
        $this->container['weekdays'] = $weekdays;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


