<?php
/**
 * Sensor
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KiwiKi\Model;

use \ArrayAccess;
use \KiwiKi\ObjectSerializer;

/**
 * Sensor Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Sensor implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Sensor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'address' => '\KiwiKi\Model\SensorAddress',
        'battery_level' => 'int',
        'battery_level_since' => '\DateTime',
        'battery_status' => 'string',
        'battery_step' => 'int',
        'can_invite' => 'bool',
        'custom_attributes' => 'object',
        'customer_name' => 'string',
        'door_type' => 'string',
        'hardware_type' => 'string',
        'hardware_variant' => 'string',
        'highest_permission' => 'string',
        'installation_date' => '\DateTime',
        'is_favorite' => 'bool',
        'is_owner' => 'bool',
        'owner' => '\KiwiKi\Model\SensorOwner',
        'sensor_id' => 'int',
        'sensor_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'address' => null,
        'battery_level' => null,
        'battery_level_since' => 'date-time',
        'battery_status' => null,
        'battery_step' => null,
        'can_invite' => null,
        'custom_attributes' => null,
        'customer_name' => null,
        'door_type' => null,
        'hardware_type' => null,
        'hardware_variant' => null,
        'highest_permission' => null,
        'installation_date' => 'date-time',
        'is_favorite' => null,
        'is_owner' => null,
        'owner' => null,
        'sensor_id' => null,
        'sensor_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'battery_level' => 'battery_level',
        'battery_level_since' => 'battery_level_since',
        'battery_status' => 'battery_status',
        'battery_step' => 'battery_step',
        'can_invite' => 'can_invite',
        'custom_attributes' => 'custom_attributes',
        'customer_name' => 'customer_name',
        'door_type' => 'door_type',
        'hardware_type' => 'hardware_type',
        'hardware_variant' => 'hardware_variant',
        'highest_permission' => 'highest_permission',
        'installation_date' => 'installation_date',
        'is_favorite' => 'is_favorite',
        'is_owner' => 'is_owner',
        'owner' => 'owner',
        'sensor_id' => 'sensor_id',
        'sensor_name' => 'sensor_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'battery_level' => 'setBatteryLevel',
        'battery_level_since' => 'setBatteryLevelSince',
        'battery_status' => 'setBatteryStatus',
        'battery_step' => 'setBatteryStep',
        'can_invite' => 'setCanInvite',
        'custom_attributes' => 'setCustomAttributes',
        'customer_name' => 'setCustomerName',
        'door_type' => 'setDoorType',
        'hardware_type' => 'setHardwareType',
        'hardware_variant' => 'setHardwareVariant',
        'highest_permission' => 'setHighestPermission',
        'installation_date' => 'setInstallationDate',
        'is_favorite' => 'setIsFavorite',
        'is_owner' => 'setIsOwner',
        'owner' => 'setOwner',
        'sensor_id' => 'setSensorId',
        'sensor_name' => 'setSensorName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'battery_level' => 'getBatteryLevel',
        'battery_level_since' => 'getBatteryLevelSince',
        'battery_status' => 'getBatteryStatus',
        'battery_step' => 'getBatteryStep',
        'can_invite' => 'getCanInvite',
        'custom_attributes' => 'getCustomAttributes',
        'customer_name' => 'getCustomerName',
        'door_type' => 'getDoorType',
        'hardware_type' => 'getHardwareType',
        'hardware_variant' => 'getHardwareVariant',
        'highest_permission' => 'getHighestPermission',
        'installation_date' => 'getInstallationDate',
        'is_favorite' => 'getIsFavorite',
        'is_owner' => 'getIsOwner',
        'owner' => 'getOwner',
        'sensor_id' => 'getSensorId',
        'sensor_name' => 'getSensorName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['battery_level'] = isset($data['battery_level']) ? $data['battery_level'] : null;
        $this->container['battery_level_since'] = isset($data['battery_level_since']) ? $data['battery_level_since'] : null;
        $this->container['battery_status'] = isset($data['battery_status']) ? $data['battery_status'] : null;
        $this->container['battery_step'] = isset($data['battery_step']) ? $data['battery_step'] : null;
        $this->container['can_invite'] = isset($data['can_invite']) ? $data['can_invite'] : null;
        $this->container['custom_attributes'] = isset($data['custom_attributes']) ? $data['custom_attributes'] : null;
        $this->container['customer_name'] = isset($data['customer_name']) ? $data['customer_name'] : null;
        $this->container['door_type'] = isset($data['door_type']) ? $data['door_type'] : null;
        $this->container['hardware_type'] = isset($data['hardware_type']) ? $data['hardware_type'] : null;
        $this->container['hardware_variant'] = isset($data['hardware_variant']) ? $data['hardware_variant'] : null;
        $this->container['highest_permission'] = isset($data['highest_permission']) ? $data['highest_permission'] : null;
        $this->container['installation_date'] = isset($data['installation_date']) ? $data['installation_date'] : null;
        $this->container['is_favorite'] = isset($data['is_favorite']) ? $data['is_favorite'] : null;
        $this->container['is_owner'] = isset($data['is_owner']) ? $data['is_owner'] : null;
        $this->container['owner'] = isset($data['owner']) ? $data['owner'] : null;
        $this->container['sensor_id'] = isset($data['sensor_id']) ? $data['sensor_id'] : null;
        $this->container['sensor_name'] = isset($data['sensor_name']) ? $data['sensor_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return \KiwiKi\Model\SensorAddress
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \KiwiKi\Model\SensorAddress $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets battery_level
     *
     * @return int
     */
    public function getBatteryLevel()
    {
        return $this->container['battery_level'];
    }

    /**
     * Sets battery_level
     *
     * @param int $battery_level battery_level
     *
     * @return $this
     */
    public function setBatteryLevel($battery_level)
    {
        $this->container['battery_level'] = $battery_level;

        return $this;
    }

    /**
     * Gets battery_level_since
     *
     * @return \DateTime
     */
    public function getBatteryLevelSince()
    {
        return $this->container['battery_level_since'];
    }

    /**
     * Sets battery_level_since
     *
     * @param \DateTime $battery_level_since battery_level_since
     *
     * @return $this
     */
    public function setBatteryLevelSince($battery_level_since)
    {
        $this->container['battery_level_since'] = $battery_level_since;

        return $this;
    }

    /**
     * Gets battery_status
     *
     * @return string
     */
    public function getBatteryStatus()
    {
        return $this->container['battery_status'];
    }

    /**
     * Sets battery_status
     *
     * @param string $battery_status battery_status
     *
     * @return $this
     */
    public function setBatteryStatus($battery_status)
    {
        $this->container['battery_status'] = $battery_status;

        return $this;
    }

    /**
     * Gets battery_step
     *
     * @return int
     */
    public function getBatteryStep()
    {
        return $this->container['battery_step'];
    }

    /**
     * Sets battery_step
     *
     * @param int $battery_step battery_step
     *
     * @return $this
     */
    public function setBatteryStep($battery_step)
    {
        $this->container['battery_step'] = $battery_step;

        return $this;
    }

    /**
     * Gets can_invite
     *
     * @return bool
     */
    public function getCanInvite()
    {
        return $this->container['can_invite'];
    }

    /**
     * Sets can_invite
     *
     * @param bool $can_invite can_invite
     *
     * @return $this
     */
    public function setCanInvite($can_invite)
    {
        $this->container['can_invite'] = $can_invite;

        return $this;
    }

    /**
     * Gets custom_attributes
     *
     * @return object
     */
    public function getCustomAttributes()
    {
        return $this->container['custom_attributes'];
    }

    /**
     * Sets custom_attributes
     *
     * @param object $custom_attributes custom_attributes
     *
     * @return $this
     */
    public function setCustomAttributes($custom_attributes)
    {
        $this->container['custom_attributes'] = $custom_attributes;

        return $this;
    }

    /**
     * Gets customer_name
     *
     * @return string
     */
    public function getCustomerName()
    {
        return $this->container['customer_name'];
    }

    /**
     * Sets customer_name
     *
     * @param string $customer_name customer_name
     *
     * @return $this
     */
    public function setCustomerName($customer_name)
    {
        $this->container['customer_name'] = $customer_name;

        return $this;
    }

    /**
     * Gets door_type
     *
     * @return string
     */
    public function getDoorType()
    {
        return $this->container['door_type'];
    }

    /**
     * Sets door_type
     *
     * @param string $door_type door_type
     *
     * @return $this
     */
    public function setDoorType($door_type)
    {
        $this->container['door_type'] = $door_type;

        return $this;
    }

    /**
     * Gets hardware_type
     *
     * @return string
     */
    public function getHardwareType()
    {
        return $this->container['hardware_type'];
    }

    /**
     * Sets hardware_type
     *
     * @param string $hardware_type hardware_type
     *
     * @return $this
     */
    public function setHardwareType($hardware_type)
    {
        $this->container['hardware_type'] = $hardware_type;

        return $this;
    }

    /**
     * Gets hardware_variant
     *
     * @return string
     */
    public function getHardwareVariant()
    {
        return $this->container['hardware_variant'];
    }

    /**
     * Sets hardware_variant
     *
     * @param string $hardware_variant hardware_variant
     *
     * @return $this
     */
    public function setHardwareVariant($hardware_variant)
    {
        $this->container['hardware_variant'] = $hardware_variant;

        return $this;
    }

    /**
     * Gets highest_permission
     *
     * @return string
     */
    public function getHighestPermission()
    {
        return $this->container['highest_permission'];
    }

    /**
     * Sets highest_permission
     *
     * @param string $highest_permission highest_permission
     *
     * @return $this
     */
    public function setHighestPermission($highest_permission)
    {
        $this->container['highest_permission'] = $highest_permission;

        return $this;
    }

    /**
     * Gets installation_date
     *
     * @return \DateTime
     */
    public function getInstallationDate()
    {
        return $this->container['installation_date'];
    }

    /**
     * Sets installation_date
     *
     * @param \DateTime $installation_date installation_date
     *
     * @return $this
     */
    public function setInstallationDate($installation_date)
    {
        $this->container['installation_date'] = $installation_date;

        return $this;
    }

    /**
     * Gets is_favorite
     *
     * @return bool
     */
    public function getIsFavorite()
    {
        return $this->container['is_favorite'];
    }

    /**
     * Sets is_favorite
     *
     * @param bool $is_favorite is_favorite
     *
     * @return $this
     */
    public function setIsFavorite($is_favorite)
    {
        $this->container['is_favorite'] = $is_favorite;

        return $this;
    }

    /**
     * Gets is_owner
     *
     * @return bool
     */
    public function getIsOwner()
    {
        return $this->container['is_owner'];
    }

    /**
     * Sets is_owner
     *
     * @param bool $is_owner is_owner
     *
     * @return $this
     */
    public function setIsOwner($is_owner)
    {
        $this->container['is_owner'] = $is_owner;

        return $this;
    }

    /**
     * Gets owner
     *
     * @return \KiwiKi\Model\SensorOwner
     */
    public function getOwner()
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param \KiwiKi\Model\SensorOwner $owner owner
     *
     * @return $this
     */
    public function setOwner($owner)
    {
        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets sensor_id
     *
     * @return int
     */
    public function getSensorId()
    {
        return $this->container['sensor_id'];
    }

    /**
     * Sets sensor_id
     *
     * @param int $sensor_id sensor_id
     *
     * @return $this
     */
    public function setSensorId($sensor_id)
    {
        $this->container['sensor_id'] = $sensor_id;

        return $this;
    }

    /**
     * Gets sensor_name
     *
     * @return string
     */
    public function getSensorName()
    {
        return $this->container['sensor_name'];
    }

    /**
     * Sets sensor_name
     *
     * @param string $sensor_name sensor_name
     *
     * @return $this
     */
    public function setSensorName($sensor_name)
    {
        $this->container['sensor_name'] = $sensor_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


