<?php
/**
 * SensorPermission
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KiwiKi\Model;

use \ArrayAccess;
use \KiwiKi\ObjectSerializer;

/**
 * SensorPermission Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SensorPermission implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SensorPermission';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'begins' => '\DateTime',
        'can_modify' => 'bool',
        'deleted' => '\DateTime',
        'ends' => '\DateTime',
        'granted' => 'string',
        'granted_by' => 'object',
        'id' => 'int',
        'sensors' => '\KiwiKi\Model\Sensor[]',
        'timeofday_begins' => 'string',
        'timeofday_ends' => 'string',
        'timing_state' => 'string',
        'users' => 'object[]',
        'weekdays' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'begins' => 'date-time',
        'can_modify' => null,
        'deleted' => 'date-time',
        'ends' => 'date-time',
        'granted' => null,
        'granted_by' => null,
        'id' => null,
        'sensors' => null,
        'timeofday_begins' => 'time',
        'timeofday_ends' => 'time',
        'timing_state' => null,
        'users' => null,
        'weekdays' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'begins' => 'begins',
        'can_modify' => 'can_modify',
        'deleted' => 'deleted',
        'ends' => 'ends',
        'granted' => 'granted',
        'granted_by' => 'granted_by',
        'id' => 'id',
        'sensors' => 'sensors',
        'timeofday_begins' => 'timeofday_begins',
        'timeofday_ends' => 'timeofday_ends',
        'timing_state' => 'timing_state',
        'users' => 'users',
        'weekdays' => 'weekdays'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'begins' => 'setBegins',
        'can_modify' => 'setCanModify',
        'deleted' => 'setDeleted',
        'ends' => 'setEnds',
        'granted' => 'setGranted',
        'granted_by' => 'setGrantedBy',
        'id' => 'setId',
        'sensors' => 'setSensors',
        'timeofday_begins' => 'setTimeofdayBegins',
        'timeofday_ends' => 'setTimeofdayEnds',
        'timing_state' => 'setTimingState',
        'users' => 'setUsers',
        'weekdays' => 'setWeekdays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'begins' => 'getBegins',
        'can_modify' => 'getCanModify',
        'deleted' => 'getDeleted',
        'ends' => 'getEnds',
        'granted' => 'getGranted',
        'granted_by' => 'getGrantedBy',
        'id' => 'getId',
        'sensors' => 'getSensors',
        'timeofday_begins' => 'getTimeofdayBegins',
        'timeofday_ends' => 'getTimeofdayEnds',
        'timing_state' => 'getTimingState',
        'users' => 'getUsers',
        'weekdays' => 'getWeekdays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const GRANTED_ADMIN = 'IS_ADMIN';
    const GRANTED_MANAGER = 'IS_MANAGER';
    const GRANTED_HOST = 'IS_HOST';
    const GRANTED_GUEST = 'IS_GUEST';
    const TIMING_STATE_ACTIVE = 'active';
    const TIMING_STATE_PENDING = 'pending';
    const TIMING_STATE_EXPIRED = 'expired';
    const TIMING_STATE_OFFDAY = 'offday';
    const TIMING_STATE_OFFHOURS = 'offhours';
    const WEEKDAYS_MONDAY = 'monday';
    const WEEKDAYS_TUESDAY = 'tuesday';
    const WEEKDAYS_WEDNESDAY = 'wednesday';
    const WEEKDAYS_THURSDAY = 'thursday';
    const WEEKDAYS_FRIDAY = 'friday';
    const WEEKDAYS_SATURDAY = 'saturday';
    const WEEKDAYS_SUNDAY = 'sunday';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getGrantedAllowableValues()
    {
        return [
            self::GRANTED_ADMIN,
            self::GRANTED_MANAGER,
            self::GRANTED_HOST,
            self::GRANTED_GUEST,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTimingStateAllowableValues()
    {
        return [
            self::TIMING_STATE_ACTIVE,
            self::TIMING_STATE_PENDING,
            self::TIMING_STATE_EXPIRED,
            self::TIMING_STATE_OFFDAY,
            self::TIMING_STATE_OFFHOURS,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getWeekdaysAllowableValues()
    {
        return [
            self::WEEKDAYS_MONDAY,
            self::WEEKDAYS_TUESDAY,
            self::WEEKDAYS_WEDNESDAY,
            self::WEEKDAYS_THURSDAY,
            self::WEEKDAYS_FRIDAY,
            self::WEEKDAYS_SATURDAY,
            self::WEEKDAYS_SUNDAY,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['begins'] = isset($data['begins']) ? $data['begins'] : null;
        $this->container['can_modify'] = isset($data['can_modify']) ? $data['can_modify'] : null;
        $this->container['deleted'] = isset($data['deleted']) ? $data['deleted'] : null;
        $this->container['ends'] = isset($data['ends']) ? $data['ends'] : null;
        $this->container['granted'] = isset($data['granted']) ? $data['granted'] : null;
        $this->container['granted_by'] = isset($data['granted_by']) ? $data['granted_by'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['sensors'] = isset($data['sensors']) ? $data['sensors'] : null;
        $this->container['timeofday_begins'] = isset($data['timeofday_begins']) ? $data['timeofday_begins'] : null;
        $this->container['timeofday_ends'] = isset($data['timeofday_ends']) ? $data['timeofday_ends'] : null;
        $this->container['timing_state'] = isset($data['timing_state']) ? $data['timing_state'] : null;
        $this->container['users'] = isset($data['users']) ? $data['users'] : null;
        $this->container['weekdays'] = isset($data['weekdays']) ? $data['weekdays'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getGrantedAllowableValues();
        if (!is_null($this->container['granted']) && !in_array($this->container['granted'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'granted', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTimingStateAllowableValues();
        if (!is_null($this->container['timing_state']) && !in_array($this->container['timing_state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'timing_state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets begins
     *
     * @return \DateTime
     */
    public function getBegins()
    {
        return $this->container['begins'];
    }

    /**
     * Sets begins
     *
     * @param \DateTime $begins begins
     *
     * @return $this
     */
    public function setBegins($begins)
    {
        $this->container['begins'] = $begins;

        return $this;
    }

    /**
     * Gets can_modify
     *
     * @return bool
     */
    public function getCanModify()
    {
        return $this->container['can_modify'];
    }

    /**
     * Sets can_modify
     *
     * @param bool $can_modify can_modify
     *
     * @return $this
     */
    public function setCanModify($can_modify)
    {
        $this->container['can_modify'] = $can_modify;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return \DateTime
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param \DateTime $deleted deleted
     *
     * @return $this
     */
    public function setDeleted($deleted)
    {
        $this->container['deleted'] = $deleted;

        return $this;
    }

    /**
     * Gets ends
     *
     * @return \DateTime
     */
    public function getEnds()
    {
        return $this->container['ends'];
    }

    /**
     * Sets ends
     *
     * @param \DateTime $ends ends
     *
     * @return $this
     */
    public function setEnds($ends)
    {
        $this->container['ends'] = $ends;

        return $this;
    }

    /**
     * Gets granted
     *
     * @return string
     */
    public function getGranted()
    {
        return $this->container['granted'];
    }

    /**
     * Sets granted
     *
     * @param string $granted granted
     *
     * @return $this
     */
    public function setGranted($granted)
    {
        $allowedValues = $this->getGrantedAllowableValues();
        if (!is_null($granted) && !in_array($granted, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'granted', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['granted'] = $granted;

        return $this;
    }

    /**
     * Gets granted_by
     *
     * @return object
     */
    public function getGrantedBy()
    {
        return $this->container['granted_by'];
    }

    /**
     * Sets granted_by
     *
     * @param object $granted_by granted_by
     *
     * @return $this
     */
    public function setGrantedBy($granted_by)
    {
        $this->container['granted_by'] = $granted_by;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets sensors
     *
     * @return \KiwiKi\Model\Sensor[]
     */
    public function getSensors()
    {
        return $this->container['sensors'];
    }

    /**
     * Sets sensors
     *
     * @param \KiwiKi\Model\Sensor[] $sensors sensors
     *
     * @return $this
     */
    public function setSensors($sensors)
    {
        $this->container['sensors'] = $sensors;

        return $this;
    }

    /**
     * Gets timeofday_begins
     *
     * @return string
     */
    public function getTimeofdayBegins()
    {
        return $this->container['timeofday_begins'];
    }

    /**
     * Sets timeofday_begins
     *
     * @param string $timeofday_begins timeofday_begins
     *
     * @return $this
     */
    public function setTimeofdayBegins($timeofday_begins)
    {
        $this->container['timeofday_begins'] = $timeofday_begins;

        return $this;
    }

    /**
     * Gets timeofday_ends
     *
     * @return string
     */
    public function getTimeofdayEnds()
    {
        return $this->container['timeofday_ends'];
    }

    /**
     * Sets timeofday_ends
     *
     * @param string $timeofday_ends timeofday_ends
     *
     * @return $this
     */
    public function setTimeofdayEnds($timeofday_ends)
    {
        $this->container['timeofday_ends'] = $timeofday_ends;

        return $this;
    }

    /**
     * Gets timing_state
     *
     * @return string
     */
    public function getTimingState()
    {
        return $this->container['timing_state'];
    }

    /**
     * Sets timing_state
     *
     * @param string $timing_state timing_state
     *
     * @return $this
     */
    public function setTimingState($timing_state)
    {
        $allowedValues = $this->getTimingStateAllowableValues();
        if (!is_null($timing_state) && !in_array($timing_state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'timing_state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['timing_state'] = $timing_state;

        return $this;
    }

    /**
     * Gets users
     *
     * @return object[]
     */
    public function getUsers()
    {
        return $this->container['users'];
    }

    /**
     * Sets users
     *
     * @param object[] $users users
     *
     * @return $this
     */
    public function setUsers($users)
    {
        $this->container['users'] = $users;

        return $this;
    }

    /**
     * Gets weekdays
     *
     * @return string[]
     */
    public function getWeekdays()
    {
        return $this->container['weekdays'];
    }

    /**
     * Sets weekdays
     *
     * @param string[] $weekdays weekdays
     *
     * @return $this
     */
    public function setWeekdays($weekdays)
    {
        $allowedValues = $this->getWeekdaysAllowableValues();
        if (!is_null($weekdays) && array_diff($weekdays, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'weekdays', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['weekdays'] = $weekdays;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


