<?php
/**
 * UserData
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KiwiKi\Model;

use \ArrayAccess;
use \KiwiKi\ObjectSerializer;

/**
 * UserData Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'user_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'country' => 'string',
        'email' => 'string',
        'i_have_read_and_accepted_kiwidotki_agb' => 'bool',
        'lang' => 'string',
        'lastname' => 'string',
        'name' => 'string',
        'password' => 'string',
        'segment_id' => 'string',
        'send_verification_mail' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'country' => null,
        'email' => 'email',
        'i_have_read_and_accepted_kiwidotki_agb' => null,
        'lang' => null,
        'lastname' => null,
        'name' => null,
        'password' => null,
        'segment_id' => null,
        'send_verification_mail' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country' => 'country',
        'email' => 'email',
        'i_have_read_and_accepted_kiwidotki_agb' => 'i_have_read_and_accepted_kiwidotki_agb',
        'lang' => 'lang',
        'lastname' => 'lastname',
        'name' => 'name',
        'password' => 'password',
        'segment_id' => 'segment_id',
        'send_verification_mail' => 'send_verification_mail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country' => 'setCountry',
        'email' => 'setEmail',
        'i_have_read_and_accepted_kiwidotki_agb' => 'setIHaveReadAndAcceptedKiwidotkiAgb',
        'lang' => 'setLang',
        'lastname' => 'setLastname',
        'name' => 'setName',
        'password' => 'setPassword',
        'segment_id' => 'setSegmentId',
        'send_verification_mail' => 'setSendVerificationMail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country' => 'getCountry',
        'email' => 'getEmail',
        'i_have_read_and_accepted_kiwidotki_agb' => 'getIHaveReadAndAcceptedKiwidotkiAgb',
        'lang' => 'getLang',
        'lastname' => 'getLastname',
        'name' => 'getName',
        'password' => 'getPassword',
        'segment_id' => 'getSegmentId',
        'send_verification_mail' => 'getSendVerificationMail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const LANG_EN = 'en';
    const LANG_DE = 'de';
    const SEGMENT_ID__00 = '00';
    const SEGMENT_ID__05 = '05';
    const SEGMENT_ID__10 = '10';
    const SEGMENT_ID__15 = '15';
    const SEGMENT_ID__20 = '20';
    const SEGMENT_ID__25 = '25';
    const SEGMENT_ID__30 = '30';
    const SEGMENT_ID__35 = '35';
    const SEGMENT_ID__40 = '40';
    const SEGMENT_ID__50 = '50';
    const SEGMENT_ID__55 = '55';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLangAllowableValues()
    {
        return [
            self::LANG_EN,
            self::LANG_DE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSegmentIdAllowableValues()
    {
        return [
            self::SEGMENT_ID__00,
            self::SEGMENT_ID__05,
            self::SEGMENT_ID__10,
            self::SEGMENT_ID__15,
            self::SEGMENT_ID__20,
            self::SEGMENT_ID__25,
            self::SEGMENT_ID__30,
            self::SEGMENT_ID__35,
            self::SEGMENT_ID__40,
            self::SEGMENT_ID__50,
            self::SEGMENT_ID__55,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['i_have_read_and_accepted_kiwidotki_agb'] = isset($data['i_have_read_and_accepted_kiwidotki_agb']) ? $data['i_have_read_and_accepted_kiwidotki_agb'] : null;
        $this->container['lang'] = isset($data['lang']) ? $data['lang'] : null;
        $this->container['lastname'] = isset($data['lastname']) ? $data['lastname'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['password'] = isset($data['password']) ? $data['password'] : null;
        $this->container['segment_id'] = isset($data['segment_id']) ? $data['segment_id'] : '10';
        $this->container['send_verification_mail'] = isset($data['send_verification_mail']) ? $data['send_verification_mail'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['country']) && (mb_strlen($this->container['country']) > 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['email']) && (mb_strlen($this->container['email']) > 127)) {
            $invalidProperties[] = "invalid value for 'email', the character length must be smaller than or equal to 127.";
        }

        $allowedValues = $this->getLangAllowableValues();
        if (!is_null($this->container['lang']) && !in_array($this->container['lang'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'lang', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['lastname'] === null) {
            $invalidProperties[] = "'lastname' can't be null";
        }
        if ((mb_strlen($this->container['lastname']) > 64)) {
            $invalidProperties[] = "invalid value for 'lastname', the character length must be smaller than or equal to 64.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 64)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 64.";
        }

        $allowedValues = $this->getSegmentIdAllowableValues();
        if (!is_null($this->container['segment_id']) && !in_array($this->container['segment_id'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'segment_id', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return $this
     */
    public function setCountry($country)
    {
        if (!is_null($country) && (mb_strlen($country) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling UserData., must be smaller than or equal to 2.');
        }

        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        if (!is_null($email) && (mb_strlen($email) > 127)) {
            throw new \InvalidArgumentException('invalid length for $email when calling UserData., must be smaller than or equal to 127.');
        }

        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets i_have_read_and_accepted_kiwidotki_agb
     *
     * @return bool
     */
    public function getIHaveReadAndAcceptedKiwidotkiAgb()
    {
        return $this->container['i_have_read_and_accepted_kiwidotki_agb'];
    }

    /**
     * Sets i_have_read_and_accepted_kiwidotki_agb
     *
     * @param bool $i_have_read_and_accepted_kiwidotki_agb i_have_read_and_accepted_kiwidotki_agb
     *
     * @return $this
     */
    public function setIHaveReadAndAcceptedKiwidotkiAgb($i_have_read_and_accepted_kiwidotki_agb)
    {
        $this->container['i_have_read_and_accepted_kiwidotki_agb'] = $i_have_read_and_accepted_kiwidotki_agb;

        return $this;
    }

    /**
     * Gets lang
     *
     * @return string
     */
    public function getLang()
    {
        return $this->container['lang'];
    }

    /**
     * Sets lang
     *
     * @param string $lang lang
     *
     * @return $this
     */
    public function setLang($lang)
    {
        $allowedValues = $this->getLangAllowableValues();
        if (!is_null($lang) && !in_array($lang, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'lang', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lang'] = $lang;

        return $this;
    }

    /**
     * Gets lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->container['lastname'];
    }

    /**
     * Sets lastname
     *
     * @param string $lastname lastname
     *
     * @return $this
     */
    public function setLastname($lastname)
    {
        if ((mb_strlen($lastname) > 64)) {
            throw new \InvalidArgumentException('invalid length for $lastname when calling UserData., must be smaller than or equal to 64.');
        }

        $this->container['lastname'] = $lastname;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        if ((mb_strlen($name) > 64)) {
            throw new \InvalidArgumentException('invalid length for $name when calling UserData., must be smaller than or equal to 64.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password password
     *
     * @return $this
     */
    public function setPassword($password)
    {
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets segment_id
     *
     * @return string
     */
    public function getSegmentId()
    {
        return $this->container['segment_id'];
    }

    /**
     * Sets segment_id
     *
     * @param string $segment_id segment_id
     *
     * @return $this
     */
    public function setSegmentId($segment_id)
    {
        $allowedValues = $this->getSegmentIdAllowableValues();
        if (!is_null($segment_id) && !in_array($segment_id, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'segment_id', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['segment_id'] = $segment_id;

        return $this;
    }

    /**
     * Gets send_verification_mail
     *
     * @return bool
     */
    public function getSendVerificationMail()
    {
        return $this->container['send_verification_mail'];
    }

    /**
     * Sets send_verification_mail
     *
     * @param bool $send_verification_mail send_verification_mail
     *
     * @return $this
     */
    public function setSendVerificationMail($send_verification_mail)
    {
        $this->container['send_verification_mail'] = $send_verification_mail;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


