<?php
/**
 * User
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KiwiKi\Model;

use \ArrayAccess;
use \KiwiKi\ObjectSerializer;

/**
 * User Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class User implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'User';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'analytics_consent' => 'bool',
        'contact' => '\KiwiKi\Model\UserContact',
        'custom_fields' => 'object',
        'email_verification_status' => 'string',
        'is_managed' => 'bool',
        'is_offline' => 'bool',
        'migration_status' => 'string',
        'organization_id' => 'int',
        'user_id' => 'int',
        'username' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'analytics_consent' => null,
        'contact' => null,
        'custom_fields' => null,
        'email_verification_status' => null,
        'is_managed' => null,
        'is_offline' => null,
        'migration_status' => null,
        'organization_id' => null,
        'user_id' => null,
        'username' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'analytics_consent' => 'analytics_consent',
        'contact' => 'contact',
        'custom_fields' => 'custom_fields',
        'email_verification_status' => 'email_verification_status',
        'is_managed' => 'is_managed',
        'is_offline' => 'is_offline',
        'migration_status' => 'migration_status',
        'organization_id' => 'organization_id',
        'user_id' => 'user_id',
        'username' => 'username'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'analytics_consent' => 'setAnalyticsConsent',
        'contact' => 'setContact',
        'custom_fields' => 'setCustomFields',
        'email_verification_status' => 'setEmailVerificationStatus',
        'is_managed' => 'setIsManaged',
        'is_offline' => 'setIsOffline',
        'migration_status' => 'setMigrationStatus',
        'organization_id' => 'setOrganizationId',
        'user_id' => 'setUserId',
        'username' => 'setUsername'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'analytics_consent' => 'getAnalyticsConsent',
        'contact' => 'getContact',
        'custom_fields' => 'getCustomFields',
        'email_verification_status' => 'getEmailVerificationStatus',
        'is_managed' => 'getIsManaged',
        'is_offline' => 'getIsOffline',
        'migration_status' => 'getMigrationStatus',
        'organization_id' => 'getOrganizationId',
        'user_id' => 'getUserId',
        'username' => 'getUsername'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const EMAIL_VERIFICATION_STATUS_NOT_STARTED = 'NOT_STARTED';
    const EMAIL_VERIFICATION_STATUS_PENDING = 'PENDING';
    const EMAIL_VERIFICATION_STATUS_COMPLETED = 'COMPLETED';
    const MIGRATION_STATUS_NOT_STARTED = 'NOT_STARTED';
    const MIGRATION_STATUS_PENDING = 'PENDING';
    const MIGRATION_STATUS_COMPLETED = 'COMPLETED';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEmailVerificationStatusAllowableValues()
    {
        return [
            self::EMAIL_VERIFICATION_STATUS_NOT_STARTED,
            self::EMAIL_VERIFICATION_STATUS_PENDING,
            self::EMAIL_VERIFICATION_STATUS_COMPLETED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMigrationStatusAllowableValues()
    {
        return [
            self::MIGRATION_STATUS_NOT_STARTED,
            self::MIGRATION_STATUS_PENDING,
            self::MIGRATION_STATUS_COMPLETED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['analytics_consent'] = isset($data['analytics_consent']) ? $data['analytics_consent'] : null;
        $this->container['contact'] = isset($data['contact']) ? $data['contact'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
        $this->container['email_verification_status'] = isset($data['email_verification_status']) ? $data['email_verification_status'] : null;
        $this->container['is_managed'] = isset($data['is_managed']) ? $data['is_managed'] : null;
        $this->container['is_offline'] = isset($data['is_offline']) ? $data['is_offline'] : null;
        $this->container['migration_status'] = isset($data['migration_status']) ? $data['migration_status'] : null;
        $this->container['organization_id'] = isset($data['organization_id']) ? $data['organization_id'] : null;
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['username'] = isset($data['username']) ? $data['username'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['contact'] === null) {
            $invalidProperties[] = "'contact' can't be null";
        }
        if ($this->container['custom_fields'] === null) {
            $invalidProperties[] = "'custom_fields' can't be null";
        }
        if ($this->container['email_verification_status'] === null) {
            $invalidProperties[] = "'email_verification_status' can't be null";
        }
        $allowedValues = $this->getEmailVerificationStatusAllowableValues();
        if (!is_null($this->container['email_verification_status']) && !in_array($this->container['email_verification_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'email_verification_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['is_managed'] === null) {
            $invalidProperties[] = "'is_managed' can't be null";
        }
        if ($this->container['is_offline'] === null) {
            $invalidProperties[] = "'is_offline' can't be null";
        }
        if ($this->container['migration_status'] === null) {
            $invalidProperties[] = "'migration_status' can't be null";
        }
        $allowedValues = $this->getMigrationStatusAllowableValues();
        if (!is_null($this->container['migration_status']) && !in_array($this->container['migration_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'migration_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['organization_id'] === null) {
            $invalidProperties[] = "'organization_id' can't be null";
        }
        if ($this->container['user_id'] === null) {
            $invalidProperties[] = "'user_id' can't be null";
        }
        if ($this->container['username'] === null) {
            $invalidProperties[] = "'username' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets analytics_consent
     *
     * @return bool
     */
    public function getAnalyticsConsent()
    {
        return $this->container['analytics_consent'];
    }

    /**
     * Sets analytics_consent
     *
     * @param bool $analytics_consent analytics_consent
     *
     * @return $this
     */
    public function setAnalyticsConsent($analytics_consent)
    {
        $this->container['analytics_consent'] = $analytics_consent;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \KiwiKi\Model\UserContact
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \KiwiKi\Model\UserContact $contact contact
     *
     * @return $this
     */
    public function setContact($contact)
    {
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object $custom_fields custom_fields
     *
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets email_verification_status
     *
     * @return string
     */
    public function getEmailVerificationStatus()
    {
        return $this->container['email_verification_status'];
    }

    /**
     * Sets email_verification_status
     *
     * @param string $email_verification_status email_verification_status
     *
     * @return $this
     */
    public function setEmailVerificationStatus($email_verification_status)
    {
        $allowedValues = $this->getEmailVerificationStatusAllowableValues();
        if (!in_array($email_verification_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'email_verification_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['email_verification_status'] = $email_verification_status;

        return $this;
    }

    /**
     * Gets is_managed
     *
     * @return bool
     */
    public function getIsManaged()
    {
        return $this->container['is_managed'];
    }

    /**
     * Sets is_managed
     *
     * @param bool $is_managed is_managed
     *
     * @return $this
     */
    public function setIsManaged($is_managed)
    {
        $this->container['is_managed'] = $is_managed;

        return $this;
    }

    /**
     * Gets is_offline
     *
     * @return bool
     */
    public function getIsOffline()
    {
        return $this->container['is_offline'];
    }

    /**
     * Sets is_offline
     *
     * @param bool $is_offline is_offline
     *
     * @return $this
     */
    public function setIsOffline($is_offline)
    {
        $this->container['is_offline'] = $is_offline;

        return $this;
    }

    /**
     * Gets migration_status
     *
     * @return string
     */
    public function getMigrationStatus()
    {
        return $this->container['migration_status'];
    }

    /**
     * Sets migration_status
     *
     * @param string $migration_status migration_status
     *
     * @return $this
     */
    public function setMigrationStatus($migration_status)
    {
        $allowedValues = $this->getMigrationStatusAllowableValues();
        if (!in_array($migration_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'migration_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['migration_status'] = $migration_status;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return int
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param int $organization_id organization_id
     *
     * @return $this
     */
    public function setOrganizationId($organization_id)
    {
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return int
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param int $user_id user_id
     *
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string $username username
     *
     * @return $this
     */
    public function setUsername($username)
    {
        $this->container['username'] = $username;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


