<?php
/**
 * PermissionDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KiwiKi;

/**
 * PermissionDataTest Class Doc Comment
 *
 * @category    Class
 * @description PermissionData
 * @package     KiwiKi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PermissionDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PermissionData"
     */
    public function testPermissionData()
    {
    }

    /**
     * Test attribute "begins"
     */
    public function testPropertyBegins()
    {
    }

    /**
     * Test attribute "ends"
     */
    public function testPropertyEnds()
    {
    }

    /**
     * Test attribute "permission"
     */
    public function testPropertyPermission()
    {
    }

    /**
     * Test attribute "sensors"
     */
    public function testPropertySensors()
    {
    }

    /**
     * Test attribute "timeofday_begins"
     */
    public function testPropertyTimeofdayBegins()
    {
    }

    /**
     * Test attribute "timeofday_ends"
     */
    public function testPropertyTimeofdayEnds()
    {
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
    }

    /**
     * Test attribute "weekdays"
     */
    public function testPropertyWeekdays()
    {
    }
}
