<?php
/**
 * SensorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KiwiKi;

/**
 * SensorTest Class Doc Comment
 *
 * @category    Class
 * @description Sensor
 * @package     KiwiKi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SensorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Sensor"
     */
    public function testSensor()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "battery_level"
     */
    public function testPropertyBatteryLevel()
    {
    }

    /**
     * Test attribute "battery_level_since"
     */
    public function testPropertyBatteryLevelSince()
    {
    }

    /**
     * Test attribute "battery_status"
     */
    public function testPropertyBatteryStatus()
    {
    }

    /**
     * Test attribute "battery_step"
     */
    public function testPropertyBatteryStep()
    {
    }

    /**
     * Test attribute "can_invite"
     */
    public function testPropertyCanInvite()
    {
    }

    /**
     * Test attribute "custom_attributes"
     */
    public function testPropertyCustomAttributes()
    {
    }

    /**
     * Test attribute "customer_name"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "door_type"
     */
    public function testPropertyDoorType()
    {
    }

    /**
     * Test attribute "hardware_type"
     */
    public function testPropertyHardwareType()
    {
    }

    /**
     * Test attribute "hardware_variant"
     */
    public function testPropertyHardwareVariant()
    {
    }

    /**
     * Test attribute "highest_permission"
     */
    public function testPropertyHighestPermission()
    {
    }

    /**
     * Test attribute "installation_date"
     */
    public function testPropertyInstallationDate()
    {
    }

    /**
     * Test attribute "is_favorite"
     */
    public function testPropertyIsFavorite()
    {
    }

    /**
     * Test attribute "is_owner"
     */
    public function testPropertyIsOwner()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "sensor_id"
     */
    public function testPropertySensorId()
    {
    }

    /**
     * Test attribute "sensor_name"
     */
    public function testPropertySensorName()
    {
    }
}
