<?php
/**
 * V1organizationsorganizationIdcustomattributesdatasensorsensorIdDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KiwiKi;

/**
 * V1organizationsorganizationIdcustomattributesdatasensorsensorIdDataTest Class Doc Comment
 *
 * @category    Class
 * @description V1organizationsorganizationIdcustomattributesdatasensorsensorIdData
 * @package     KiwiKi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1organizationsorganizationIdcustomattributesdatasensorsensorIdDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1organizationsorganizationIdcustomattributesdatasensorsensorIdData"
     */
    public function testV1organizationsorganizationIdcustomattributesdatasensorsensorIdData()
    {
    }

    /**
     * Test attribute "attrib_key"
     */
    public function testPropertyAttribKey()
    {
    }
}
