<?php
/**
 * OrganizationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.49
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace KiwiKi;

use \KiwiKi\Configuration;
use \KiwiKi\ApiException;
use \KiwiKi\ObjectSerializer;

/**
 * OrganizationApiTest Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrganizationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomAttributesDataSensorSensorIdGet
     *
     * Get an organization sensor's custom attributes data.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomAttributesDataSensorSensorIdGet()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomAttributesDataSensorSensorIdPost
     *
     * Edit an organization sensor's attribute (one or multiple).
     *
     */
    public function testV1OrganizationsOrganizationIdCustomAttributesDataSensorSensorIdPost()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomAttributesSensorAttribKeyDelete
     *
     * Delete an organization's custom attribute.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomAttributesSensorAttribKeyDelete()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomAttributesSensorAttribKeyPost
     *
     * Edit an organization's custom attribute label.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomAttributesSensorAttribKeyPost()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomAttributesSensorGet
     *
     * Get a list of organization's custom attributes.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomAttributesSensorGet()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomAttributesSensorPost
     *
     * Create an organization's custom attribute.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomAttributesSensorPost()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsFieldIdGet
     *
     * Get a user's custom field.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsFieldIdGet()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsFieldIdManageDelete
     *
     * Delete an organization's custom field.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsFieldIdManageDelete()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsFieldIdManagePost
     *
     * Edit organization's custom field name.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsFieldIdManagePost()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsFieldIdPost
     *
     * Edit user's custom field value.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsFieldIdPost()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsGet
     *
     * Get a list of organization's custom fields.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsGet()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsPost
     *
     * Create an organization's custom field.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsPost()
    {
    }

    /**
     * Test case for v1OrganizationsOrganizationIdCustomFieldsUserUserIdGet
     *
     * Get a list of the user's custom fields.
     *
     */
    public function testV1OrganizationsOrganizationIdCustomFieldsUserUserIdGet()
    {
    }
}
