<?php
/**
 * SensorApiTest
 * PHP version 5
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The KIWI API
 *
 * This is the documentation for the HTTP API provided by KIWI.KI GmbH for remote unlocking and administration of doors. This API can be used for integration into existing systems and for application development.
 *
 * OpenAPI spec version: 1.0.0 (Stable)
 * Contact: api@kiwi.ki
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.27
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace KiwiKi;

use \KiwiKi\Configuration;
use \KiwiKi\ApiException;
use \KiwiKi\ObjectSerializer;

/**
 * SensorApiTest Class Doc Comment
 *
 * @category Class
 * @package  KiwiKi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SensorApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1FriendlyNamesSensorSensorIdPost
     *
     * Assign a custom name to a sensor (friendly name).
     *
     */
    public function testV1FriendlyNamesSensorSensorIdPost()
    {
    }

    /**
     * Test case for v1SensorsGet
     *
     * Get a list of visible sensors.
     *
     */
    public function testV1SensorsGet()
    {
    }

    /**
     * Test case for v1SensorsSensorIdActActionPost
     *
     * Send a command to a sensor.
     *
     */
    public function testV1SensorsSensorIdActActionPost()
    {
    }

    /**
     * Test case for v1SensorsSensorIdGet
     *
     * Get sensor details.
     *
     */
    public function testV1SensorsSensorIdGet()
    {
    }

    /**
     * Test case for v1SensorsSensorIdPermissionsGet
     *
     * Get sensor permissions.
     *
     */
    public function testV1SensorsSensorIdPermissionsGet()
    {
    }
}
